### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by mcooley-school** [Oakraven79/pavlov_rcon_tcl#9]
While launching the most recent exe release on windows 10 (full sysinfo attached) a dialogue box would open then immediately close.
After launching it in terminal I was able to find the error code:
```
G:\Users\ToastyCrumpet\Downloads\temp\rcon pavlov\rcon .75>PavlovRcon.exe
Traceback (most recent call last):
  File "main.py", line 29, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "async_app.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "tkinter\__init__.py", line 36, in <module>
ImportError: DLL load failed while importing _tkinter: The specified module could not be found.
[9640] Failed to execute script 'main' due to unhandled exception! 
```
[sys info.txt](https://github.com/Oakraven79/pavlov_rcon_tcl/files/7530919/sys.info.txt)

**I was able to resolve this by simply downloading source and launching main.py with python.**

PS: Love your tool to death, makes running a local server so much easier and fun. Only thing I would ask you to add would be scrolling through the weapons menu, its kind of a pain to use the arrow keys everytime I want to give everyone an rpg.

**Comment by Oakraven79** [comment]
Hey Just getting time to this. 

Interesting exception, have not seen that before. Will try replicate. 

Am looking at scrollable things for the weapons menu. Will comment here when I have a resolution. 

Cheers!
